
application:
  image:
    repository: spx01/blocky
    tag: latest
    pullPolicy: IfNotPresent
  config:
    upstreams:
      groups:
        default:
          - 8.8.8.8
          - 8.8.4.4
    blocking:
      denylists:
        ads: []
      clientGroupsBlock:
        default:
          - ads
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  nodeSelector: {}
  affinity: {}
  tolerations: []
  
controller:
  image:
    repository: teegank/blocky-controller
    tag: latest
    pullPolicy: IfNotPresent
  config:
    watchDNSMappings: true
    updateInterval: 15000
    retryInterval: 30000
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  nodeSelector: {}
  affinity: {}
  tolerations: []

dnsService:
  enabled: true
  type: LoadBalancer
  additionalProperties: {}

webService:
  enabled: true
  type: ClusterIP
  additionalProperties: {}

dashboard:
  enabled: true
  domain: ""
  ipAddress: ""

dnsMappings: []