apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blocky-controller-read-dnsmappings
subjects:
- kind: ServiceAccount
  name: blocky-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: read-dnsmappings
  apiGroup: rbac.authorization.k8s.io