apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: blocky
data:
  config.yml: |-
    {{- toYaml ( merge ( dict "ports" ( dict "http" 4000 "dns" 53 ) ) .Values.application.config ) | nindent 4 }}