apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: blocky
data:
  config.yml: |-
    upstreams:
      groups:
        default:
{{ toYaml .Values.application.config.upstreamDnsServers | indent 10}}
    blocking:
      denylists:
        ads:
{{ toYaml .Values.application.config.blockLists | indent 10}}
      clientGroupsBlock:
        default:
          - ads
    ports:
      http: 4000
      dns: 53
    customDNS:
      customTTL: 1h
      filterUnmappedTypes: true