{{- range $mapping := $.Values.dnsMappings }}
---
apiVersion: blocky.io/v1
kind: DnsMapping
metadata:
  name: {{ $mapping.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $mapping.labels }}
  labels:
    {{- toYaml $mapping.labels | nindent 4 }}
{{- end }}
spec:
  domain: {{ $mapping.domain }}
  ipAddress: {{ $mapping.ipAddress }}
{{- end }}