apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blocky-controller-rollout-restart-deployments
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: blocky-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: rollout-restart-deployments
  apiGroup: rbac.authorization.k8s.io