apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blocky-controller-read-write-configmaps
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: blocky-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: read-write-configmaps
  apiGroup: rbac.authorization.k8s.io