{{- if .Values.webService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: blocky-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: blocky
spec:
  type: {{ .Values.webService.type | default "ClusterIP" }}
  selector:
    app: blocky
  ports:
    - name: http
      port: {{ .Values.webService.httpPort | default 80 }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.webService.httpsPort | default 443 }}
      targetPort: http
      protocol: TCP
  {{- if .Values.webService.additionalProperties }}
  {{- toYaml .Values.webService.additionalProperties | nindent 2 }}
  {{- end }}
{{- end -}}